name: Github Actions CI for Veil
on: [push, pull_request]
env:
  SOURCE_ARTIFACT: source
jobs:
  create-source-distribution:
    name: Create Source Distribution
    runs-on: ubuntu-18.04
    env:
      ARTIFACT_DIR: source
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Install Required Packages
      run: |
        ls doc/man
        sudo apt list --installed
        sudo apt-get update
        sudo apt-get install -y libboost-all-dev libdb-dev libdb++-dev libevent-dev
    - name: Create Distribution Tarball
      run: |
        ls doc/man
        ./autogen.sh
        ./configure --with-incompatible-bdb
        make dist
    - name: Download Dependencies
      run: make -C depends download
    - name: Create Dependencies Tarball
      run: tar -czf depends.tar.gz depends
    - name: Prepare Files for Artifact
      run: |
        mkdir -p $ARTIFACT_DIR
        mv depends.tar.gz veil-*.tar.gz $ARTIFACT_DIR
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.SOURCE_ARTIFACT }}
        path: ${{ env.ARTIFACT_DIR }}
  build-arm-linux:
    name: Build for ARM 64 Linux
    needs: create-source-distribution
    runs-on: ubuntu-18.04
    env:
      ARTIFACT_DIR: aarch64_linux-binaries
    steps:
    - name: Getting Source
      uses: actions/download-artifact@v1
      with:
        name: ${{ env.SOURCE_ARTIFACT }}
    - name: Extract Archives
      run: |
        tar -xzf depends.tar.gz
        tar -xzf veil-*.tar.gz --strip-components=1
        ls doc/man
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Install Required Packages
      run: |
        sudo apt-get update
        sudo apt-get upgrade
        sudo apt-get install -y python3-zmq g++-aarch64-linux-gnu cmake libqrencode-dev
    - name: Build Dependencies
      run: make -C depends -j$(nproc) HOST=aarch64-linux-gnu
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Setup Configuration
      run: |
        ./autogen.sh
        ./configure --disable-jni --with-comparison-tool=no --with-gui=yes --prefix=$(realpath depends/aarch64-linux-gnu)
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Build Veil
      run: |
        ls doc/man
        make -C doc/man -j$(nproc)
      working-directory: ${{ env.SOURCE_ARTIFACT }}
    - name: Prepare Files for Artifact
      run: |
        mkdir -p $ARTIFACT_DIR
#        strip $SOURCE_ARTIFACT/src/{veil-cli,veil-tx,veild,qt/veil-qt}
#        mv $SOURCE_ARTIFACT/src/{veil-cli,veil-tx,veild,qt/veil-qt} $ARTIFACT_DIR
    - name: Upload Artifact
      uses: actions/upload-artifact@v1
      with:
        name: ${{ env.ARTIFACT_DIR }}
        path: ${{ env.ARTIFACT_DIR }}
